---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cert-manager-aws-credentials
  namespace: cert-manager
spec:
  encryptedData:
    aws-access-key-id: AgAM1FNtbr90Bp3RrBkn1zRXynH5jeR7hCqeM1ZVRGEHB96qQXIb9veKlRnKgLpevTY8MKRYHSUOVb+MfBBkvE7+5Ah8oMKYit/1mpNtelpdzM+bsg8W6kKoIt3oXPKlB5LchDeJRYw+cMCdOa6HgDnYOo+MQy1bJ8Y/8lbQwFEx3+si7KaIe5bwOFzG82D76rNuqL1zLZpQ+Fr6pzopGUXMf67kPPYJUJbo3WFah2V1plUnbonKjx+5I0L/ELiPgciXf57XERmmlmEkiyfNaKulbgSRG0uRzd93vEi7Lhhz26OycN3w3amegrSraCKpc6RffXknBHp0YxqfB3viaLbz7tbhZDaEiYqdfPcjjzgUREuagJo4yJMFoS3xV3CJzfEsseFJjFTMVi3NDeOeaKuRaFU3Ihl5yVgGta6Pd667FdecJZReSnYAwVK19/A0lxKWvjtG0dhLtFvrPPN8wMd4zoWgPLTwqPcVng9NtmV1KydT+FBUsrN8rNyXpOgT7DlK1hq4oC5LOmuMn74tcpYIZorJ6hfkzVjQQcYqIxEXW3X4/3LsqCuui9jZWMuPYpeGrw9xQ+6DuM8kk+TmY1UsaLJE5NAjo6jPYlcCBr/mPPCa6KtnoLiNz9yPbtLMLfRvVZtd5tAKD+o/zd9g5UEJbheZxvAC99auupnwP+5eJ5b2+pFN1kTDNd7eoj9R6mh/EY7V4ifSdN/heLVPLd9md3DS7A==
    aws-secret-access-key: AgCOSYa8g2rpzAB45gGdUo5YT+1s5vanldvzsBdnHv0HQjJK0HLZZsAbj8yktI8Lwb2nhOtmg2OUts0qd+ENbu0ceFPuCZS+x53pWDQZyTZ7R59ZQu/JBXWSOXxwJh33SGA8kv9kp9f6eOGqYEYxjSMHt2jXB9ufjTvXFK2pkaPJjSezVJnSrk6jwvdrt/pigKAiXdgVB9JKifUjUTjx0Jmooq6bFzlP0ukdkkptD0kfUdCg7Ts+II3O431XD209RttSo77jr2fGA3GEebPfp9kRC6ZbtklfsvbmazV6w0qP6X/s5F7/OAAGG+velVFaMM+Xzd5Pnze+BaO1i1k8IcWgP/FOiRicmCscMJMHKreXnvOzjE/VMzP2i3O9KaFBLFylVvHmvSlQpENzEkKCGDSLxF8M4a0LSDPB2Rigj0TskRD5Y9I5g/0S2fkya7uK74aoolnmurt0rfTYw2VCE4eaeRYAPOCuFCrmco/fU7E4lgN9GhpUvxL+5/ULwM7fK3IE3UBaHjSoHIzpPxsn7eyKBb2cPV/KKNYMwnCFdUAMLJFCKr6gqOhRRCyhnk8BDJW702QERUAYvFD6l6oTWl2UoeBlpkp3gz/mrMXNd69D9emPggHEp7o+Hj5K8TK0xwU5auZyR89IISSnhiIMqAMdUsQAZZE/76D76xj43MIiSszyAkl+GO5ZOTkOkGyoiLyoX8I/Umh2Cx0dru0Mh1wKLuxKdrK6ArYZRQD9tjR9KUknyBARLcpq
  template:
    metadata:
      creationTimestamp: null
      name: cert-manager-aws-credentials
      namespace: cert-manager
